# Generated by Django 5.2 on 2025-06-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Berth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("berth_number", models.PositiveIntegerField(unique=True)),
                (
                    "berth_type",
                    models.CharField(
                        choices=[
                            ("LOWER", "Lower"),
                            ("MIDDLE", "Middle"),
                            ("UPPER", "Upper"),
                            ("SIDE_LOWER", "Side Lower"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("has_child", models.BooleanField(default=False)),
                ("is_child", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("RAC", "RAC"),
                            ("WAITING", "Waiting List"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "berth_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOWER", "Lower"),
                            ("MIDDLE", "Middle"),
                            ("UPPER", "Upper"),
                            ("SIDE_LOWER", "Side Lower"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("berth_number", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.passenger"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RACSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.PositiveIntegerField(unique=True)),
                (
                    "passenger_1",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rac_passenger_1",
                        to="api.ticket",
                    ),
                ),
                (
                    "passenger_2",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rac_passenger_2",
                        to="api.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(unique=True)),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ticket"
                    ),
                ),
            ],
        ),
    ]
